### PR TITLE
TRITON-2445 mdata-client doesn't handle short writes

### PR DESCRIPTION
**Pull request by jperkin**

### CODE REVIEW

**Comment by tsoome** [comment]
There is a problem in your implementation -- if len is > SSIZE_MAX, illumos is documented to set errno to EINVAL; if partial writes are ok, I'd suggest to split such writes till we fit into ssize. Also it seems EFBIG is not handled.

**Comment by jperkin** [comment]
True, although I should point out that it is highly unusual for any mdata request to be more than 1KB or so (e.g. a large number of SSH public keys).  Even attempting these ~1MB requests takes around 3 minutes for each PUT/GET.  Anything this size or larger would be impractical in real life usage due to serial port constraints.  This is more about handling common write errors that might show up, rather than actually attempting to support such sized values.

**Comment by tsoome** [comment]
> True, although I should point out that it is highly unusual for any mdata request to be more than 1KB or so (e.g. a large number of SSH public keys). Even attempting these ~1MB requests takes around 3 minutes for each PUT/GET. Anything this size or larger would be impractical in real life usage due to serial port constraints. This is more about handling common write errors that might show up, rather than actually attempting to support such sized values.

I see, ok so we error out and have respective errno value. Seems good.

**Review by tsoome — APPROVED** [review]

**Comment by danmcd** [comment]
I am SO sorry this didn't get examined for pulling in.  Stirred the internal pot again.

**Review by danmcd — APPROVED** [review]
Gonna pull this in, finally!

**Pull request merged**
